### ISSUE TITLE
Failure with https://github.com/dlang/dmd/pull/9817

### ISSUE THREAD

**Issue by thewilsonator** [aliak00/optional#33]
https://github.com/aliak00/optional/blob/master/tests/notnull.d#L105 fails with https://github.com/dlang/dmd/pull/9817

Just a heads up, haven't looked into it properly.

**Comment by aliak00** [comment]
Thanks for the heads up!! Initially, i'm actually not sure how to handle this 😬 will try and figure something out when I have more time though.

**Comment by thewilsonator** [comment]
No problem, if I can help just let me know.

**Comment by aliak00** [comment]
Thanks! Yes, if you can think of a work around for the issue, that'd be awesome :D 

The problem stems from a property that returns an encapsulated value by ref. It used to not compile before when (I'm not actually sure why now, it seems like it should've compiled 🤔 ) but now it does so you can alter the ref value inside.

Though I don't understand the patch in dmd completely. Does it convert a ref to a temp and pass the temp? So the temp is the thing that would be altered? Because then I guess there's no problem really. I think.

**Comment by aliak00** [comment]
Turns out this is a symptom of a bigger problem with `NotNull`! 

fixed in 56a3a122f37e95d6f427909a6bc3cb5d400d8aae
